### ISSUE TITLE
Multilevel of nested flexbox in navbar Header.svelte?

### ISSUE THREAD

**Issue by HEYROCKME** [sveltejs/kit-template-default#2]
Now we got three elements <nav>, <ul> and <a> all given a {display:flex;} to position the links in the navigation. 

Is there any reason to use nested flexbox beyond the unorderer list in the <ul>?

**Comment by Conduitry** [comment]
The contents of this repo are automatically generated from the main https://github.com/sveltejs/kit repo. Any issues or PRs shoul be opened there.
