### ISSUE TITLE
svelte@latest  Omitting environment variable "CommonProgramFiles(x86)"

### ISSUE THREAD

**Issue by alanxp** [sveltejs/kit-template-default#3]
Not sure if there was a new version, just upgraded npm create svelte@latest and after npm install i get this almost at the end of installation

1258 verbose stack Error: command failed
1258 verbose stack     at ChildProcess.<anonymous> (C:\Users\alan\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
1258 verbose stack     at ChildProcess.emit (node:events:513:28)
1258 verbose stack     at maybeClose (node:internal/child_process:1091:16)
1258 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
1259 verbose pkgid @sveltejs/kit@1.0.0-next.407
1260 verbose cwd D:\OneDrive\Documentos\Proyects Factory\htdocs\testapp
1261 verbose Windows_NT 10.0.22000
1262 verbose node v18.7.0
1263 verbose npm  v8.12.1

1264 error code 1
1265 error path D:\OneDrive\Documentos\Proyects Factory\htdocs\testapp\node_modules\@sveltejs\kit
1266 error command failed
1267 error command C:\WINDOWS\system32\cmd.exe /d /s /c node svelte-kit.js sync
1268 error Omitting environment variable "CommonProgramFiles(x86)" from $env/static/private as it is not a valid identifier
1268 error Omitting environment variable "npm_package_bin_svelte-kit" from $env/static/private as it is not a valid identifier
1268 error Omitting environment variable "ProgramFiles(x86)" from $env/static/private as it is not a valid identifier
1268 error > src/routes/+page.svelte references missing layout "sveltejs/kit/src/runtime/components/layout"
1268 error     at trace (file:///D:/OneDrive/Documentos/Proyects%20Factory/htdocs/testapp/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:377:9)
1268 error     at file:///D:/OneDrive/Documentos/Proyects%20Factory/htdocs/testapp/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:185:34
1268 error     at Array.forEach (<anonymous>)
1268 error     at create_manifest_data (file:///D:/OneDrive/Documentos/Proyects%20Factory/htdocs/testapp/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:60:39)
1268 error     at create (file:///D:/OneDrive/Documentos/Proyects%20Factory/htdocs/testapp/node_modules/@sveltejs/kit/src/core/sync/sync.js:25:24)
1268 error     at Module.all (file:///D:/OneDrive/Documentos/Proyects%20Factory/htdocs/testapp/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:15)
1268 error     at file:///D:/OneDrive/Documentos/Proyects%20Factory/htdocs/testapp/node_modules/@sveltejs/kit/src/cli.js:71:15
1269 verbose exit 1
1270 timing npm Completed in 25344ms
1271 verbose unfinished npm timer reify 1660606279904
1272 verbose unfinished npm timer reify:build 1660606303302
1273 verbose unfinished npm timer build 1660606303303
1274 verbose unfinished npm timer build:deps 1660606303304
1275 verbose unfinished npm timer build:run:postinstall 1660606303458
1276 verbose unfinished npm timer build:run:postinstall:node_modules/@sveltejs/kit 1660606303459
1277 verbose code 1
1278 error A complete log of this run can be found in:
1278 error     C:\Users\alan\AppData\Local\npm-cache\_logs\2022-08-15T23_31_19_773Z-debug-0.log

**Comment by Conduitry** [comment]
The contents of this repo are automatically generated from the main https://github.com/sveltejs/kit repo. Any issues or PRs shoul be opened there.
