### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by RobinKnipe** [sveltejs/kit-template-default#7]
I've just tried to create a new `bun` project using:

```shell
bun create svelte@latest
```

It seems there's a dependency mismatch somewhere, bun fails to install, npm completes with a warning:

```shell
$ bun i
bun install v1.0.26 (c75e768a)
warn: incorrect peer dependency "svelte@5.0.0-next.48"

error: No version matching ">=0.34.0-next.4 <1.0.0" found for specifier "svelte-eslint-parser" (but package exists)

$ npm i
npm WARN ERESOLVE overriding peer dependency

added 228 packages, and audited 229 packages in 41s
```

**Comment by benmccann** [comment]
If this problem persists with the Svelte 5 final release, please file at https://github.com/sveltejs/cli

**Comment by Conduitry** [comment]
I'm going to go ahead and close this. This is a generated repo, and the source for this template lives elsewhere.
